version: '3.8'

services:
  web:
    build: app/
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
